### ISSUE TITLE
missing csrf checks on action/custom forms.

### ISSUE THREAD

**Issue by danmarsden** [braincert/moodle-mod_braincert#4]
When you implement your own html forms or "action" style handlers you need to implement sesskey checking - more info here:
https://docs.moodle.org/dev/Security:Cross-site_request_forgery#What_you_need_to_do_in_your_code

**Comment by braincert** [comment]
Fixed.

**Comment by danmarsden** [comment]
no it isn't. I can still see custom actions that do not check for sesskey in your code.

**Comment by arvinddubey** [comment]
Corrected and fixed it. Thanks.

**Comment by developerck** [comment]
there is only one custom form  and that has a sesskey check. So marking this issue close.
