### ISSUE TITLE
hard coded english language strings

### ISSUE THREAD

**Issue by danmarsden** [braincert/moodle-mod_braincert#9]
https://github.com/braincert/Moodle-HTML5-Virtual-Classroom-Plugin/blob/master/adddiscount.php#L52

please review all strings and make sure they are in the lang files.

**Comment by danmarsden** [comment]
that was only one example - there are a lot more:
https://github.com/braincert/Moodle-HTML5-Virtual-Classroom-Plugin/blob/master/view.php#L323

**Comment by braincert** [comment]
This is now fixed. Thanks.

**Comment by danmarsden** [comment]
I can still see hard-coded english language strings in your code.

**Comment by arvinddubey** [comment]
All the hard coded language strings have been moved to the language file. Thanks.

**Comment by pkExec** [comment]
As of 2020, there are still hardcoded strings for example here: 
https://github.com/braincert/moodle-mod_braincert/blob/master/mod_form.php

Timezones, Days, Time strings, Languages, Recurrence options etc.

**Comment by developerck** [comment]
Now we hve changed all, Some of them has been put caps in string file, jsut because the symbolize that.
